[package]
name = "praktikum-algorithmik"
version = "0.1.0"
authors = ["Elias Wendt <elias.wendt@de-cix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
